[book]
title = "faang-dsa"
src = "book-src"
language = "en"

[output]

[output.html]
default-theme = "gruvbox"
preferred-dark-theme = "gruvbox"
additional-css = ["gruvbox/css/variables.css", "gruvbox/highlight.css"]
additional-js = ["gruvbox/gruvbox.js"]

[output.html.fold]
enable = true
level = 1
