[project]
name = "faang-dsa"
version = "0.1.0"
description = "dsa prep in Python for internship, co-op, and new-grad interviews at big tech companies"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.3",
]

[dependency-groups]
dev = [
    "mdformat>=0.7.22",
    "mdformat-gfm>=0.4.1",
    "ruff>=0.11.13",
]

[tool.mdformat]
wrap = 88

[tool.pytest.ini_options]
pythonpath = [
    "01_arrays_and_hashing",
    "02_two_pointers",
    "03_stack",
    "04_sliding_window",
    "05_binary_search",
    "06_linked_lists",
    "07_trees",
    "08_heaps",
    "09_backtracking",
    "10_graphs",
    "11_dp",
    "12_greedy_algorithms",
    "13_intervals",
    "14_tries",
    "15_bit_manipulation",
    "16_math_geometry",
    "17_advanced",
    "18_mixed_interview_practice",
    "other/problem_sets/01_grid_bfs",
]
testpaths = [
    "01_arrays_and_hashing",
    "02_two_pointers",
    "03_stack",
    "04_sliding_window",
    "05_binary_search",
    "06_linked_lists",
    "07_trees",
    "08_heaps",
    "09_backtracking",
    "10_graphs",
    "11_dp",
    "12_greedy_algorithms",
    "13_intervals",
    "14_tries",
    "15_bit_manipulation",
    "16_math_geometry",
    "17_advanced",
    "18_mixed_interview_practice",
    "other/problem_sets"
]

[tool.ruff]
line-length = 130
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pyright]
typeCheckingMode = "off"
reportUnknownArgumentType = "none"
reportUnknownMemberType = "none"
reportUnknownParameterType = "none"
reportUnknownVariableType = "none"
reportMissingParameterType = "none"

[[tool.pyright.executionEnvironments]]
root = "."
extraPaths = [
    "01_arrays_and_hashing",
    "02_two_pointers",
    "03_stack",
    "04_sliding_window",
    "05_binary_search",
    "06_linked_lists",
    "07_trees",
    "08_heaps",
    "09_backtracking",
    "10_graphs",
    "11_dp",
    "12_greedy_algorithms",
    "13_intervals",
    "14_tries",
    "15_bit_manipulation",
    "16_math_geometry",
    "17_advanced",
    "other/problem_sets/01_grid_bfs",
]
